{{- if .Values.standalone.horizontalPodAutoscaler.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Release.Name }}-standalone"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Release.Name }}-server"
  minReplicas: {{ .Values.standalone.horizontalPodAutoscaler.minReplicas }}
  maxReplicas: {{ .Values.standalone.horizontalPodAutoscaler.maxReplicas }}
  behavior: {{ .Values.standalone.horizontalPodAutoscaler.behavior}}
  metrics: {{ .Values.standalone.horizontalPodAutoscaler.metrics }}
{{- end }}
