apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-env"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  # server settings
  {{- with .Values.settings.server }}
  {{- include "app.secretValue" ( dict "Key" "APP_SERVER_HOSTNAME" "Value" .hostname ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_SERVER_PORT" "Value" .host ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_SERVER_HOST" "Value" .port ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_SERVER_GZIP" "Value" .useCompression ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_SERVER_SERVE_STATIC" "Value" .serveStatic ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_SERVER_STATIC_DIRECTORY" "Value" .staticDirectory ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_SERVER_JSON_LIMIT" "Value" .jsonLimit ) }}
  {{- end }}

  # health monitor settings
  {{- with .Values.settings.healthMonitor }}
  {{- include "app.secretValue" ( dict "Key" "APP_HEALTH_MONITOR_ENABLED" "Value" .enabled ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_HEALTH_MONITOR_HOST" "Value" .host ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_HEALTH_MONITOR_PORT" "Value" .port ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_HEALTH_MONITOR_INTERVAL" "Value" .interval ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_HEALTH_MONITOR_VERBOSE" "Value" .verbose ) }}
  {{- end }}

  # prometheus export settings
  {{- with .Values.settings.prometheusExport }}
  {{- include "app.secretValue" ( dict "Key" "APP_USE_PROMETHEUS_EXPORT" "Value" .enabled ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_PROMETHEUS_EXPORT_HOST" "Value" .host ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_PROMETHEUS_EXPORT_PORT" "Value" .port ) }}
  {{- end }}

  # proxy settings
  {{- with .Values.settings.proxy }}
  {{- include "app.secretValue" ( dict "Key" "HTTP_PROXY" "Value" .httpProxy ) }}
  {{- include "app.secretValue" ( dict "Key" "HTTPS_PROXY" "Value" .httpsProxy ) }}
  {{- end }}

  # sentry settings
  {{- with .Values.settings.sentry }}
  {{- include "app.secretValue" ( dict "Key" "APP_SENTRY_DSN" "Value" .dsn ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_SENTRY_TRACING" "Value" .useTracing ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_SENTRY_PROFILING" "Value" .useProfiling ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_SENTRY_SAMPLE_RATE" "Value" .sentrySampleRate ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_SENTRY_RELEASE" "Value" .sentryRelease ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_SENTRY_REPLAY" "Value" .useReplay ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_SENTRY_REPLAY_SAMPLE_RATE" "Value" .sentryReplaySampleRate ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_SENTRY_DEBUG" "Value" .useSentryDebug ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_SENTRY_PROFILING_SAMPLE_RATE" "Value" .sentryProfilingRate ) }}
  {{- end }}

  # session settings
  {{- with .Values.settings.session }}
  {{- include "app.secretValue" ( dict "Key" "APP_SESSION_SECRET" "Value" .secret ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_SESSION_EXPIRES_IN" "Value" .expiresIn ) }}
  {{- end }}

  # global settings
  {{- include "app.secretValue" ( dict "Key" "APP_ENVIRONMENT" "Value" .Values.settings.environment ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_VERSION" "Value" .Values.settings.appVersion ) }}

  # spa settings
  {{- with .Values.settings.spa }}
  {{- include "app.secretValue" ( dict "Key" "APP_SPA_APOLLO_DEV_TOOLS" "Value" .apolloDevToolsEnabled ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_SPA_CONSOLE_CDN" "Value" .consoleCdn ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_SPA_CONSOLE_MANIFEST" "Value" .consoleManifest ) }}
  {{- end }}

  # database settings
  {{- with .Values.settings.database }}
  {{- include "app.secretValue" ( dict "Key" "APP_DB_URI" "Value" .databaseUri ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_DB_NAME" "Value" .databaseName ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_DB_POOL" "Value" .poolSize ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_DB_AUTH_MECHANISM" "Value" .authMechanism ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_DB_CRYPTD_URI" "Value" .cryptdUri ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_DB_CRYPTD_BYPASS_SPAWN" "Value" .cryptdBypassSpawn ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_DB_CRYPTD_SPWAN_ARGS" "Value" .cryptdSpawnArgs ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_DB_ENCRYPTION_MODE" "Value" .encryptionMode ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_DB_ENCRYPTION_KEY_VAULT_NAME" "Value" .encryptionKeyVaultDatabaseName ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_DB_ENCRYPTION_KEY_VAULT_COLLECTION_NAME" "Value" .encryptionKeyVaultCollectionName ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_DB_MASTER_KEY" "Value" .encryptionMasterKey ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_DB_AWS_KEY_ARN" "Value" .encryptionAwsKeyArn ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_DB_AWS_REGION" "Value" .awsRegion ) }}
  {{- end }}

  # redis settings
  {{- if .Values.redis.enabled }}
  {{- $redisServiceName := printf "%s-master" (include "common.names.fullname" .Subcharts.redis) }}
  {{- $redisServicePort := (add .Subcharts.redis.Values.master.service.ports.redis 0) }}
  {{- $redisUri := printf "redis://%s-redis-master.%s.svc.cluster.local:6379" .Release.Name .Release.Namespace  }}
  APP_REDIS_URI: {{ printf $redisUri  | b64enc }}
  {{- else }}
  {{- include "app.secretValue" ( dict "Key" "APP_REDIS_URI" "Value" .Values.settings.redis.uri ) }}
  {{- end }}

  # auth settings
  {{- with .Values.settings.auth }}
  {{- include "app.secretValue" ( dict "Key" "APP_AUTH_LOCAL_SALT" "Value" .localSalt ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_AUTH_LOCAL_PAST_PWDS" "Value" .localPreviousPasswords ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_AUTH_LOCAL_MIN_LENGTH" "Value" .localMinimumLength ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_AUTH_LOCAL_DURATION" "Value" .localPasswordDuration ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_AUTH_MSAL_INSTANCE" "Value" .msalCloudInstance ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_AUTH_MSAL_TENANT_ID" "Value" .msalTenantId ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_AUTH_MSAL_CLIENT_ID" "Value" .msalClientId ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_AUTH_MSAL_CLIENT_SECRET" "Value" .msalClientSecret ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_AUTH_MSAL_GRAPH_ENDPOINT" "Value" .msalGraphEndpoint ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_AUTH_PASSKEY_RP_NAME" "Value" .passKeyRpName ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_AUTH_PASSKEY_RP_ID" "Value" .passKeyRpId ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_AUTH_PASSKEY_ORIGIN" "Value" .passKeyOrigin ) }}
  {{- end }}

  # bull settings
  {{- with .Values.settings.bull }}
  {{- include "app.secretValue" ( dict "Key" "APP_BULL_REDIS_URI" "Value" .redisUri ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_BULL_QUEUE_NAME" "Value" .queueName ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_BULL_JOB_RETENTION" "Value" .jobRetention ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_BULL_CLEAN_UP_JOB_INTERVAL" "Value" .cleanUpJobInterval ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_BULL_CLEAN_UP_JOB_CRON" "Value" .cleanUpJobCron ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_USE_BULL_BOARD" "Value" .useBoard ) }}
  {{- end }}

  # broker settings
  {{- with .Values.settings.broker }}
  {{- include "app.secretValue" ( dict "Key" "APP_BROKER_TRANSPORTER_URI" "Value" .transporterUri ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_BROKER_NAMESPACE" "Value" .namespace ) }}
  {{- end }}

  # guard settings
  {{- with .Values.settings.guard }}
  {{- include "app.secretValue" ( dict "Key" "APP_GUARD_IMPLEMENTATION" "Value" .implementation ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_GUARD_CLOUDWATCH_LOG_GROUP" "Value" .cloudwatchLogGroup ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_GUARD_CLOUDWATCH_LOG_STREAM_PREFIX" "Value" .cloudwatchLogStreamPrefix ) }}
  {{- end }}

  # email settings
  {{- with .Values.settings.email }}
  {{- include "app.secretValue" ( dict "Key" "APP_EMAIL_SMTP_PORT" "Value" .smtp.port ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_EMAIL_SMTP_HOST" "Value" .smtp.host ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_EMAIL_SMTP_SECURE" "Value" .smtp.secure ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_EMAIL_SMTP_USER" "Value" .smtp.user ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_EMAIL_SMTP_PASSWORD" "Value" .smtp.password ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_EMAIL_SENDER" "Value" .sender ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_EMAIL_PROVIDER" "Value" .provider ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_EMAIL_SES_API_VERSION" "Value" .ses.apiVersion ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_EMAIL_SES_REGION" "Value" .ses.region ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_EMAIL_SES_SENDING_RATE" "Value" .ses.sendingRate ) }}
  {{- end }}

  # storage settings
  {{- with .Values.settings.storage }}
  {{- include "app.secretValue" ( dict "Key" "APP_STORAGE_AWS_IDENTITY" "Value" .awsIdentity ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_STORAGE_ACCESS_KEY" "Value" .accessKey ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_STORAGE_SECRET_KEY" "Value" .secretKey ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_STORAGE_REGION" "Value" .region ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_STORAGE_ENDPOINT" "Value" .endpoint ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_STORAGE_BUCKET" "Value" .bucket ) }}
  {{- include "app.secretValue" ( dict "Key" "APP_STORAGE_FORCE_PATH_STYLE" "Value" .forcePathStyle ) }}
  {{- end }}
