FROM cypress/browsers:node-22.14.0-chrome-134.0.6998.88-1-ff-136.0.1-edge-134.0.3124.51-1

# install build dependencies
RUN apt-get update && apt-get install python3 make g++ curl -y && rm -rf /var/lib/apt/lists/*
